import pygame

# FIXME can I even do multiple initializations?
pygame.init()

CONF_UI_FONT_SIZE = 16

DEBUG_FONT = pygame.font.SysFont("Fira Code Medium", CONF_UI_FONT_SIZE, bold=True)

CONF_WINDOW_WIDTH = 1280
CONF_WINDOW_HEIGHT = 720
CONF_WINDOW_TITLE = "Isometric Trading Game"
CONF_BACKGROUND_COLOR = (30, 30, 30)  # Dark gray
CONF_FPS = 60

CONF_CONSOLE_COLOR = (39, 28, 69)
CONF_CONSOLE_INPUT_STRIP_COLOR = (116, 105, 145)
CONF_CONSOLE_FONT_COLOR = (255, 255, 255)
CONF_CONSOLE_FONT_SIZE = 14
CONF_CONSOLE_FONT_WIDTH = 11  # Assumed for 14 size font
CONF_CONSOLE_TOP_LEFT = (10, 10)
CONF_CONSOLE_HEIGHT_PERCENT = 0.30
CONF_CONSOLE_APPEAR_TIME = 2.0

# Do not change this values (for now)
CONF_CONSOLE_POINTS_BOTTOM_LEFT = (CONF_CONSOLE_TOP_LEFT[0], CONF_CONSOLE_TOP_LEFT[1] + int(CONF_WINDOW_WIDTH * CONF_CONSOLE_HEIGHT_PERCENT))
CONF_CONSOLE_POINTS = [
        CONF_CONSOLE_TOP_LEFT,
        (CONF_WINDOW_WIDTH - CONF_CONSOLE_TOP_LEFT[0], CONF_CONSOLE_TOP_LEFT[1]),
        (CONF_WINDOW_WIDTH - CONF_CONSOLE_TOP_LEFT[0], CONF_CONSOLE_TOP_LEFT[1] + int(CONF_WINDOW_WIDTH * CONF_CONSOLE_HEIGHT_PERCENT)),
        CONF_CONSOLE_POINTS_BOTTOM_LEFT]

CONF_CONSOLE_INPUT_STRIP_POINTS = [
        (CONF_CONSOLE_POINTS_BOTTOM_LEFT[0], CONF_CONSOLE_POINTS_BOTTOM_LEFT[1] - CONF_CONSOLE_FONT_SIZE),
        (CONF_WINDOW_WIDTH - CONF_CONSOLE_POINTS_BOTTOM_LEFT[0], CONF_CONSOLE_POINTS_BOTTOM_LEFT[1] - CONF_CONSOLE_FONT_SIZE),
        (CONF_WINDOW_WIDTH - CONF_CONSOLE_POINTS_BOTTOM_LEFT[0], CONF_CONSOLE_POINTS_BOTTOM_LEFT[1]),
        CONF_CONSOLE_POINTS_BOTTOM_LEFT,
        ]

CONF_CONSOLE_CURSOR_COLOR = (227, 197, 116)

